<div class="container">


    <div class="card margin-vertical-xlarge clearfix">

        <h2 class="text-center">Availability Tracker</h2>

        <hr>

        <p>
            Click and drag mouse to select/deselect schedule blocks.
        </p>

        <table class="table text-center">
            <thead id="schedule-container-header"></thead>
            <tbody id="schedule-container"></tbody>
        </table>

        <button id="button-update-schedule" class="button button-info no-margin margin-top-medium float-right">
            Update Schedule
        </button>

    </div>

</div>