<div class="container">

    <div class="card margin-vertical-xlarge">

        <h2 class="text-center">Batch Membership Request</h2>

        <hr>

        <p>
            You are currently not part of the current active batch. There is nothing you can do by this time. If you have any concerns
            or if you want to be a part of the active batch, please talk directly to any of the frontmen.
        </p>

        <strong>Thank you!</strong>

    </div>

</div>