'index':
    controller: PublicPagesController
'login':
    controller: PublicPagesController
    function: Login
'signup':
    controller: PublicPagesController
    function: signup

'action/login':
    controller: UserActionController
    function: Login
'action/logout':
    controller: UserActionController
    function: Logout
'action/signup':
    controller: UserActionController
    function: Signup

'home':
    controller: UserPagesController
