<!DOCTYPE html>
<html>
    <head>
        <title>Signup</title>
    </head>
    <body>
        <form action="addUser.php" method="post" role="form" class="form-inline">
            <input type="email" name="email" placeholder="E-mail">
            <input type="text" name="username" placeholder="Username">
            <input type="password" name="password" placeholder="Password">
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </body>
</html>