<div class="container">

    <div class="card margin-vertical-xlarge">

        <h2 class="text-center">Member Management</h2>

        <hr>

        <div id="name-search-bar-container" class="form-group">
            <input type="text" class="form-input" id="name-search-bar" placeholder="Search for a name here...">
        </div>

        <ul id="member-list" class="list list-striped"></ul>

    </div>

</div>