<div class="container">

    <div class="card margin-vertical-xlarge">

        <h2 class="text-center">Finance Tracker</h2>

        <hr>

        <h3 class="text-center">
            The ledger for this academic year is now closed.
        </h3>

        <table class="table table-compact">
            <thead>
                <tr>
                    <th colspan="8">
                        <h3 class="no-margin">Current Batch Ledger Entries</h3>
                    </th>
                </tr>
                <tr>
                    <th width="10%">Date</th>
                    <th width="20%">Finance Member</th>
                    <th width="20%">Description</th>
                    <th width="10%">Debit</th>
                    <th width="10%">Credit</th>
                    <th width="10%">Projected Total</th>
                    <th width="10%">Verified Total</th>
                </tr>
            </thead>
            <tbody id="ledger-entries-container"></tbody>
        </table>

    </div>

</div>