<div class="container">

    <div class="card margin-vertical-xlarge">

        <h2 class="text-center">Finance Tracker</h2>

        <hr>

        <table class="table table-compact">
            <thead>
                <tr>
                    <th width="15%">Date</th>
                    <th width="20%">Finance Member</th>
                    <th width="20%">Descrition</th>
                    <th width="15%">Debit</th>
                    <th width="15%">Credit</th>
                    <th width="15%">Total</th>
                </tr>
            </thead>
            <tbody id="ledger-entries-container"></tbody>
        </table>

    </div>

</div>