<div class="container" id="batch-details-container" data-batch-id="<?= $page['details']['batch_id'] ?>">

    <div class="card">

        <div class="breadcrumb">
            <span class="crumb">
                <a href="<?= $page['urls']['index'] ?>" >Batch</a>
            </span>
            <span class="crumb">
                <span class="batch-name"></span>
            </span>
        </div>

        <hr>

        <h2>Batch <span class="batch-name"></span></h2>

    </div>

</div>