<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <title>Login</title>

        <link href="<?=base_url('assets/css/vendor/bootstrap.css')?>" rel="stylesheet">
    </head>

    <body style="background-color: pink;">
        <ul>
            <li><a href="<?=base_url('admin/change-password')?>">Edit Password</a></li>
            <li><a href="<?=base_url('admin/manage/batch')?>">Batch Management</a></li>
            <!--li><a href="<?=base_url('admin/managefrontman')?>">1st Frontman Management</a></li-->
    </body>
</html>