<div class="container">

    <div class="card margin-top-large">

        <h2 class="text-center">Members</h2>

        <hr>

        <table>
            <thead>
                <th>ID</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Email Address</th>
                <th>Phone Number</th>
            </thead>
            <tbody id="member-list" class="">

            </tbody>
        </table>

    </div>

</div>